AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy an EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 # This is an example Amazon Linux 2 AMI ID. Replace with the desired AMI ID.
      KeyName: MyEC2KeyPair # Replace with your key pair name
      SecurityGroups:
        - Ref: MyEC2SecurityGroup

  MyEC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 # Warning: This allows SSH access from any IP. Consider restricting it.

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: 
      Ref: MyEC2Instance
  PublicIP:
    Description: The public IP address
    Value: 
      Fn::GetAtt:
        - MyEC2Instance
        - PublicIp